setw -g aggressive-resize off

set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"

set -g set-titles on
set -g mode-keys vi
set -g mouse on
set -g status-position top
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 10000
set -g renumber-windows on
set-option -g focus-events on

bind-key b copy-mode\;\
           send-keys -X start-of-line\;\
           send-keys -X search-backward "❯"
bind r source-file ~/.config/tmux/tmux.conf
bind x kill-pane
bind & kill-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @plugin 'erikw/tmux-dark-notify'
set -g @dark-notify-theme-path-light '$HOME/.config/tmux/theme/light.tmux'
set -g @dark-notify-theme-path-dark '$HOME/.config/tmux/theme/dark.tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.config/tmux/plugins/tpm/tpm'

if-shell "test -e ~/.local/state/tmux/tmux-dark-notify-theme.conf" \
     "source-file ~/.local/state/tmux/tmux-dark-notify-theme.conf"

setw -g aggressive-resize off
