" .vimrc
" Author: Florian Lücke

" leader {{{
let mapleader="\<Space>"
let maplocalleader="\<Space>"
" }}}

" load plugins {{{
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!mkdir -p ~/.vim/plugged'
    execute '!mkdir -p ~/.vim/autoload'
    " Download the actual plugin manager
    execute '!curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')

Plug 'EinfachToll/DidYouMean'
Plug 'bumaociyuan/vim-swift', {'for': 'swift'}
Plug 'chrisbra/Colorizer'
Plug 'chrisbra/csv.vim'
Plug 'fluecke/dot.vim', {'for': 'dot'}
Plug 'junegunn/vim-easy-align'
Plug 'lervag/vimtex'
Plug 'lifepillar/vim-solarized8'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'tomasr/molokai'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-git', {'for': 'git'}
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-markdown'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
if has('python') || has('python3')
    Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
endif

filetype plugin indent on
call plug#end()
" }}}

" bundle settings {{{

" airline {{{
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_powerline_fonts = 1
let g:airline_right_alt_sep = ''
let g:airline_section_b = '%<%f'
let g:airline_section_c = '%{&modified?"":""}%{&readonly?"":""}'
let g:airline_section_z = '%3p％   %l/%L   %2v'
let airline#extensions#default#section_use_groupitems = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
" }}}

" undotree.vim {{{
let g:undotree_WindowLayout = 3
let g:undotree_SplitWidth = 45
" }}}

" ultisnips {{{
if has('python') && (v:version >= 704)
    let g:UltiSnipsExpandTrigger = "<tab>"
    let g:UltiSnipsJumpForwardTrigger = "<tab>"
    let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
endif
" }}}

" vim-latex {{{
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_manual = 1
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '@line @pdf @tex'

" }}}

" markdown {{{
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'ruby']
" }}}
" }}}

" vim settings {{{

let g:python3_host_prog="/usr/local/bin/python3"

augroup reload_vimrc
    autocmd!
    autocmd bufwritepost $MYVIMRC nested source $MYVIMRC
augroup END

if has('nvim')
    set ttimeout
    set ttimeoutlen=0
    if $TERM_PROGRAM =~ "iTerm"
        set mouse=
        set background=dark
        set termguicolors
        colorscheme solarized8
    else
        colorscheme molokai
        let g:airline_theme="badwolf"
    endif
    tnoremap <Esc> <C-\><C-n>
else
    colorscheme molokai
    let g:airline_theme="badwolf"
endif

" use utf-8
scriptencoding utf-8

language en_US

set hidden
set number          " enable line numbers
set shell=bash
set backspace=indent,eol,start  " make backspace work as expected

let g:tex_flavor = "latex"      " tex files are latex files
let g:sh_fold_enabled=1
set scrolloff=2     " keep two lines above and below
set sidescrolloff=5

set autoread        " reload files that were changed
set backupcopy=yes

autocmd BufEnter * let &titlestring = 'vim ' . expand("%:t")
set title

set laststatus=2    " always show statusbar
set noshowmode
set showtabline=2

" configure listchars {{{
set list
set listchars-=eol:$            " do not show newlines
set listchars+=tab:\ ,extends:>,precedes:<     " indicate long lines
" }}}

" cursorline settings {{{
" show cursorline in active buffer
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END
" }}}

" tabs, spaces, wrapping {{{
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set smarttab
" }}}

" indenting {{{
set cindent
set smartindent
set autoindent
" }}}

" wildmenu {{{
set wildmode=longest,full
set wildmenu

set wildignore+=.DS_Store                       " on OS X
set wildignore+=.git                            " version control
set wildignore+=*.bcf,*.run.xml,*.fdb_latexmk   " Latex files
set wildignore+=*.out,*.toc,*.bbl,*.fls,*.blg   " more Latex files
set wildignore+=*.aux                           " even more Latex files
set wildignore+=*.jpg,*.gif,*.bmp,*.png,*.jpeg  " images
set wildignore+=*.class,*.jar                   " java files
set wildignore+=*.log
set wildignore+=*.pdf
set wildignore+=*.gz*,*.tar,*.zip                " archives
" }}}

" return to the same line when reopening a file {{{
augroup line_return
    au!
    au BufReadPost *
        \ if line("'\"") > 0 && line("'\"") < line("$") |
        \       execute 'normal! g`"zvzz' |
        \ endif
augroup END
" }}}

" backup {{{
set undodir=~/.vim/tmp/undo//
set undofile
set nobackup
set noswapfile
set history=1000
" }}}

" search {{{
set ignorecase
set smartcase
set showmatch
set hlsearch
set incsearch
" }}}

" don't beep {{{
set visualbell
set noerrorbells
" }}}

" keymappings {{{
inoremap jk <ESC>

" don't move on *
nnoremap * *<C-o>

" go to end with <C-e> in command-line mode
cnoremap <C-e> <end>
" go to start with <C-a> in command-line mode
cnoremap <C-a> <home>

cmap w!! w !sudo tee > /dev/null %

" remove highlights with C-c in normal mode
nmap <silent> <C-c> :let @/ = ""<CR>

nnoremap q: :q
nnoremap Q <NOP>

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" prevent using arrow keys {{{
map <up> <nop>
map <down> <nop>

nnoremap <silent> <Left> :bprev<CR>
nnoremap <silent> <Right> :bnext<CR>
inoremap <silent> <Left> <C-o>:bprev<CR>
inoremap <silent> <Right> <C-o>:bnext<CR>

" }}}
" }}}

let g:terminal_color_0  = '#002833'
let g:terminal_color_1  = '#dc322f'
let g:terminal_color_2 = '#586e75'
let g:terminal_color_3 = '#657b83'
let g:terminal_color_4 = '#839496'
let g:terminal_color_5 = '#6c6ec6'
let g:terminal_color_6 = '#93a1a1'
let g:terminal_color_7 = '#fdf6e3'
let g:terminal_color_8  = '#003541'
let g:terminal_color_9  = '#cb4b16'
let g:terminal_color_10  = '#859901'
let g:terminal_color_11  = '#b58901'
let g:terminal_color_12  = '#268bd2'
let g:terminal_color_13  = '#d33682'
let g:terminal_color_14  = '#2aa198'
let g:terminal_color_15  = '#eee8d5'
" }}}

" vim:fdm=marker:
